variables:
    VPC_NAME:
        required: true
        description: the name of the VPC
        default: acceptance-test-vpc
    VPC_OCTETS:
        required: true
        description: the /16 net of the VPC to look for - i.e 10.11.0.0
        default: 10.66.0.0
    REGION:
        required: true
        description: use default except for multiple region use cases
        default: "PLAN::region"
        type: string
    PRIVATE_ROUTE_NAME:
        required: true
        description: the name to give to the private route
        default: acceptance-test-private-route
    PRIVATE_SUBNET_NAME:
        required: true
        description: the cloudcoreo name of the private vpc subnets
        default: acceptance-test-private-subnet
    PUBLIC_ROUTE_NAME:
        required: true
        description: the name to give to the public route
        default: acceptance-test-public-route
    PUBLIC_SUBNET_NAME:
        required: true
        description: the cloudcoreo name of the public vpc subnets
        default: acceptance-test-public-subnet
    PUBLIC_SUBNET_NUM_ZONES:
        default: 1
        description: the number of public subnet zones
        required: true
        type: number
    SUFFIX:
        required: false
        description: when used will use the value to suffix the names of all converged objects
        type: string
    VPC_TAGS:
        required: false
        description: tags to apply to the vpc
        type: array
        default:
            - acceptance-test
    AUDIT_AWS_CLOUDTRAIL_ALERT_LIST:
        description: "Which alerts would you like to check for? (Default is all Cloudtrail alerts)"
        required: true
        type: array
        default:
            - cloudtrail-service-disabled
            - cloudtrail-no-global-trails
            - cloudtrail-inventory
            - cloudtrail-trail-with-global
    AUDIT_AWS_CLOUDTRAIL_ALLOW_EMPTY:
        description: "Would you like to receive empty reports? Options - true / false. Default is false."
        required: true
        type: boolean
        default: true
    AUDIT_AWS_CLOUDTRAIL_SEND_ON:
        description: "Send reports always or only when there is a change? Options - always / change. Default is change."
        required: true
        type: string
        default: "change"
    AUDIT_AWS_CLOUDTRAIL_ALERT_RECIPIENT:
        description: "Enter the email address(es) that will receive notifications. If more than one, separate each with a comma."
        required: false
        type: string
        default:
    AUDIT_AWS_CLOUDTRAIL_REGIONS:
        description: "List of AWS regions to check. Default is us-east-1,us-east-2,us-west-1,us-west-2,eu-west-1."
        required: true
        type: array
        default:
            - us-east-1
            - us-east-2
            - us-west-1
            - us-west-2
            - eu-west-1
    AUDIT_AWS_CLOUDTRAIL_ROLLUP_REPORT:
        description: "Would you like to send a rollup Cloudtrail report? This is a short email that summarizes the number of checks performed and the number of violations found. Options - notify / nothing. Default is nothing."
        required: true
        type: string
        default: "nothing"
    AUDIT_AWS_CLOUDTRAIL_HTML_REPORT:
        description: "Would you like to send a full Cloudtrail report? This is an email that details any violations found and includes a list of the violating cloud objects. Options - notify / nothing. Default is nothing."
        required: true
        type: string
        default: "nothing"
    AUDIT_AWS_CLOUDTRAIL_OWNER_TAG:
        description: "Enter an AWS tag whose value is an email address of the owner of the Cloudtrail object. (Optional)"
        required: false
        type: string
        default: "NOT_A_TAG"
    TOMCAT_GROUP_MAXIMUM:
        default: 1
        description: Minimum number of instances the autoscale group will launch
        overrides:
        required: true
        type: number
    TOMCAT_GROUP_MINIMUM:
        default: 1
        description: Maximum number of instances the autoscale group will launch
        overrides:
        required: true
        type: number
    TOMCAT_INGRESS_CIDRS:
        default: 
            - 0.0.0.0/0
        description: null
        overrides: null
        required: true
        type: array
    TOMCAT_INGRESS_CIDR_PORTS:
        default:
            - 8080
            - 80
            - 443
            - 22
        description:
        overrides:
        required: true
        type: array
    TOMCAT_INGRESS_GROUP_PORTS:
        default:
        - 8080
        - 80
        - 443
        description:
        overrides:
        required: true
        type: array
    TOMCAT_KEYPAIR:
        default:
        description:
        overrides:
        required: true
        type:
    TOMCAT_NAME:
        default: ac-cat
        description:
        overrides:
        required: true
        type:
    TOMCAT_SIZE:
        default: t2.micro
        description:
        overrides:
        required: true
        type:
    YUM_REPO_BUCKET:
        default:
        description:
        overrides:
        required: false
        type:
    VPC_CIDR:
        default: 10.66.0.0/16
        description: The CIDR to match to locate the VPC that this server is to be created in
        overrides: null
        required: true
        type: string
