## This file was auto-generated by CloudCoreo CLI
## This file was automatically generated using the CloudCoreo CLI
##
## This config.rb file exists to create and maintain services not related to compute.
## for example, a VPC might be maintained using:
##
## coreo_aws_vpc_vpc "my-vpc" do
##   action :sustain
##   cidr "12.0.0.0/16"
##   internet_gateway true
## end
##


# TEMPORARY - COPY THESE FROM BASE STACK SO THEY DONT GET OVERRIDDEN
#
coreo_aws_vpc_vpc "${VPC_NAME}${SUFFIX}" do
  action :sustain
  cidr "${VPC_OCTETS}/16"
  internet_gateway true
  region "${REGION}"
  tags ${VPC_TAGS}
end
coreo_aws_vpc_routetable "${PUBLIC_ROUTE_NAME}${SUFFIX}" do
  action :sustain
  vpc "${VPC_NAME}${SUFFIX}"
  routes [
             { :from => "0.0.0.0/0", :to => "${VPC_NAME}${SUFFIX}", :type => :igw }
        ]
  number_of_tables 1
  region "${REGION}"
end
coreo_aws_vpc_subnet "${PUBLIC_SUBNET_NAME}${SUFFIX}" do
  action :sustain
  number_of_zones ${PUBLIC_SUBNET_NUM_ZONES}
  percent_of_vpc_allocated 25
  route_table "${PUBLIC_ROUTE_NAME}${SUFFIX}"
  vpc "${VPC_NAME}${SUFFIX}"
  map_public_ip_on_launch true
  region "${REGION}"
end

coreo_aws_rule "cloudtrail-inventory" do
  action :nothing
  service :cloudtrail
  link "http://kb.cloudcoreo.com/mydoc-inventory.html"
  include_violations_in_count false
  display_name "Cloudtrail Inventory"
  description "This rule performs an inventory on all trails in the target AWS account."
  category "Inventory"
  suggested_action "None."
  level "Informational"
  meta_cis_id "99.999"
  objectives ["trails"]
  audit_objects ["object.trail_list.name"]
  operators ["=~"]
  raise_when [//]
  id_map "object.trail_list.name"
end

coreo_aws_rule "cloudtrail-service-disabled" do
  action :nothing
  service :cloudtrail
  link "http://kb.cloudcoreo.com/mydoc_cloudtrail-service-disabled.html"
  display_name "Cloudtrail Service is Disabled"
  description "CloudTrail logging is not enabled for this region. It should be enabled."
  category "Audit"
  suggested_action "Enable CloudTrail logs for each region."
  level "Warning"
  meta_cis_id "99.998"
  objectives ["trails"]
  formulas ["count"]
  audit_objects ["trail_list"]
  operators ["=="]
  raise_when [0]
  id_map "stack.current_region"
end

# the jsrunner puts cloudtrail in for the service

