## This file was auto-generated by CloudCoreo CLI
## This file was automatically generated using the CloudCoreo CLI
##
## This config.rb file exists to create and maintain services not related to compute.
## for example, a VPC might be maintained using:
##
## coreo_aws_vpc_vpc "my-vpc" do
##   action :sustain
##   cidr "12.0.0.0/16"
##   internet_gateway true
## end
##


# TEMPORARY - COPY THESE FROM BASE STACK SO THEY DONT GET OVERRIDDEN
#
coreo_aws_vpc_vpc "${VPC_NAME}${SUFFIX}" do
  action :sustain
  cidr "${VPC_OCTETS}/16"
  internet_gateway true
  region "${REGION}"
  tags ${VPC_TAGS}
end
coreo_aws_vpc_routetable "${PUBLIC_ROUTE_NAME}${SUFFIX}" do
  action :sustain
  vpc "${VPC_NAME}${SUFFIX}"
  routes [
             { :from => "0.0.0.0/0", :to => "${VPC_NAME}${SUFFIX}", :type => :igw }
        ]
  number_of_tables 1
  region "${REGION}"
end
coreo_aws_vpc_subnet "${PUBLIC_SUBNET_NAME}${SUFFIX}" do
  action :sustain
  number_of_zones ${PUBLIC_SUBNET_NUM_ZONES}
  percent_of_vpc_allocated 25
  route_table "${PUBLIC_ROUTE_NAME}${SUFFIX}"
  vpc "${VPC_NAME}${SUFFIX}"
  map_public_ip_on_launch true
  region "${REGION}"
end
